### ISSUE TITLE
如何获取选中的文件信息放入formData

### ISSUE THREAD

**Issue by turionboy** [lw1995/quill-video-image-module#3]
调用第3方存储接口，上传之前需要获取token,并把选择的文件放入formData中，获取token操作是放入headers还是change方法中，测试发现是先执行上传再获取token操作了，选取的图片或视频如何获取放入我自定的formData中，随token一并上传到第3方接口，谢谢。

**Comment by lw1995** [comment]
name: 'img',//上传文件参数名
              action: 'http://127.0.0.1:5000/upload/img', // 文件上传接口
              change: (xhr, formData) => {
		formData.append('token', '你的token');
	      },

**Comment by turionboy** [comment]
> 
> 
> ```
>           name: 'img',//上传文件参数名
>           action: 'http://127.0.0.1:5000/upload/img', // 文件上传接口
>           change: (xhr, formData) => {
> 	formData.append('token', '你的token');
>       },
> ```

方便加个联系方式吗，有尝服务，谢谢

**Comment by lw1995** [comment]
Qq530174854



---原始邮件---
发件人: "turionboy"<notifications@github.com&gt;
发送时间: 2020年6月25日(周四) 晚上9:58
收件人: "lw1995/quill-video-image-module"<quill-video-image-module@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"liwei"<530174854@qq.com&gt;;
主题: Re: [lw1995/quill-video-image-module] 如何获取选中的文件信息放入formData (#3)




            name: 'img',//上传文件参数名           action: 'http://127.0.0.1:5000/upload/img', // 文件上传接口           change: (xhr, formData) =&gt; { formData.append('token', '你的token');       },   
方便加个联系方式吗，有尝服务，谢谢

**Comment by turionboy** [comment]
> 
> Qq530174854
> […](#)
> ---原始邮件--- 发件人: "turionboy"<notifications@github.com&gt; 发送时间: 2020年6月25日(周四) 晚上9:58 收件人: "lw1995/quill-video-image-module"<quill-video-image-module@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"liwei"<530174854@qq.com&gt;; 主题: Re: [lw1995/quill-video-image-module] 如何获取选中的文件信息放入formData (#3) name: 'img',//上传文件参数名 action: 'http://127.0.0.1:5000/upload/img', // 文件上传接口 change: (xhr, formData) =&gt; { formData.append('token', '你的token'); }, 方便加个联系方式吗，有尝服务，谢谢 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.



> 
> Qq530174854
> […](#)
> ---原始邮件--- 发件人: "turionboy"<notifications@github.com&gt; 发送时间: 2020年6月25日(周四) 晚上9:58 收件人: "lw1995/quill-video-image-module"<quill-video-image-module@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"liwei"<530174854@qq.com&gt;; 主题: Re: [lw1995/quill-video-image-module] 如何获取选中的文件信息放入formData (#3) name: 'img',//上传文件参数名 action: 'http://127.0.0.1:5000/upload/img', // 文件上传接口 change: (xhr, formData) =&gt; { formData.append('token', '你的token'); }, 方便加个联系方式吗，有尝服务，谢谢 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by turionboy** [comment]
> 
> Qq530174854
> […](#)
> ---原始邮件--- 发件人: "turionboy"<notifications@github.com&gt; 发送时间: 2020年6月25日(周四) 晚上9:58 收件人: "lw1995/quill-video-image-module"<quill-video-image-module@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"liwei"<530174854@qq.com&gt;; 主题: Re: [lw1995/quill-video-image-module] 如何获取选中的文件信息放入formData (#3) name: 'img',//上传文件参数名 action: 'http://127.0.0.1:5000/upload/img', // 文件上传接口 change: (xhr, formData) =&gt; { formData.append('token', '你的token'); }, 方便加个联系方式吗，有尝服务，谢谢 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

已+，谢谢

**Comment by lw1995** [comment]
扣扣530174854



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2020年6月25日(周四) 晚上9:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lw1995/quill-video-image-module] 如何获取选中的文件信息放入formData (#3)




            name: 'img',//上传文件参数名           action: 'http://127.0.0.1:5000/upload/img', // 文件上传接口           change: (xhr, formData) =&gt; { formData.append('token', '你的token');       },   
方便加个联系方式吗，有尝服务，谢谢
